### ISSUE TITLE
[Feature] Add Navigation bar with dummy screens

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-grocery-store-webapp#10]
## Stories
- User can browse all products.
- User can browse filtered products by its category, subcategory, name, price ranges.
- User can look up details of product.
- User can submit an order form.

## Tasks
- [x] Set up React Navigation
- [x] Add `AppBar` with `Logo`: Clicking `Logo` should bring users to default `Browse` screen
- [x] Add `SideNavigation`
  - Fetch categories and subcategories from API
  - No more than 1 subcategory list can be shown at once.
- [x] Add `Browse` screen
- [x] Add `ProductDetails` screen
- [x] Add `Checkout` screen

## Important
These screens are for navigation only. There will be no content on it.
