### ISSUE TITLE
[Feature] Add `ShoppingCart` component

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-grocery-store-webapp#12]
## Stories
- User can add items into shopping cart.
- User can modify quantity of items in shopping cart.
- User can drop items from shopping cart.
- User can see total quantity, total price of items in shopping cart.
- User can checkout with filled shopping cart.

## Tasks
- [x] Add shopping cart floating button at the bottom right of the screen.
  - This button can be seen on `Browse` screen and `ProductDetails` screen.
  - Should display total quantity of items in shopping cart.
- [x] Display shopping cart modal on clicking the floating button. Also closes with button.
- [x] Add empty shopping cart UI
  - Empty shopping cart disables `Checkout` button
- [x] Add `ShoppingCartItem` component
  - Quantity of item can be modified. Minimum 1, Maximum MIN(20, in stock quantity)
  - Item can be dropped
- [x] Activate `Add to Cart` buttons in `Browse` screen.
- [x] Display total quantity and total price of items.
- [x] Clicking `Clear` button drops all items in shopping cart.
- [x] Clicking `Checkout` button navigates to `Checkout` screen.
  - Once `Checkout` button is clicked, all other pages except `Checkout` screen will be blocked to be accessed.
  - Show alert popup when user tries to leave `Checkout` screen.
  - Redirect all other pages to `Checkout` screen.
- [x] All items in shopping cart should be save on local storage as well.
  - Load items from local storage on app starting.
