### ISSUE TITLE
[Feature] `Checkout` screen

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-grocery-store-webapp#14]
## Stories
- User can place an order if shopping cart is not empty.
- User can recieve order details after completing an order.

## Tasks
- [x] `Place Order` button should be disabled until all the form fields being filled out.
- [x] Validate all form fields.
- [x] If the user clicks `Place Order` button, request the order using API.
  - Button should display loading status while requesting.
- [x] Display success popup after the order is placed. Redirect to default `Browse` screen.
