### ISSUE TITLE
[Feature] GET `Category` and `Subcategory` list with `Product` count

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-grocery-store-webapp#3]
User should be able to get a list of `Category` and its `Subcategory` with `Product` count belonged in.

## Entities
1. `Category`
- `Category` has 0 or more `Subcategory`. This will be used as top-level categories in navigation bar.

2. `Subcategory`
- `Subcategory` has 0 or more `Product`. This will be use as second-level categories in navigation bar.

3. `Product`
- Every `Product` belongs to 1 `Category` - `Subcategory`.  

## Tasks
1. DB Table SQL
- [x] `RESET_DATABASE.sql` : Drop all tables in the database.
- [x] `INIT_CATEGORY_TABLE.sql` : Create `CATEGORY` Table with its dummy data.
  - At least 5 `Category` rows should be inserted.
- [x] `INIT_SUBCATEGORY_TABLE.sql` : Create `SUBCATEGORY` table with its dummy data.
  - At least 4 `Subcategory` rows for each `Category` should be inserted.
- [x] `INIT_PRODUCT_TABLE.sql` : Create `PRODUCT` table with its dummy data.
  - At least 10 `Product` rows for each `Subcategory` should be inserted.

2. Endpoint for navigation list
- [x] Organise tree of `Category` and `Subcategory` with `Product` count belonged it.
- [x] Allow fetching the list of it by requsting `GET /categories`.

3. Filter category list
- [x] Allow filtering category list with params
  - `name=`: filter by `name` including query.
  - `priceLow=` : filter by `unit_price`, inclusive.
  - `priceHight=` : filter by `unit_price`, inclusive.
