### ISSUE TITLE
[Feature] Add design system

### ISSUE THREAD

**Issue by zake-dev** [zake-dev/online-grocery-store-webapp#9]
## Tasks
- [x] Add color system
- [x] Add typography system
- [x] Add button components
- [x] Add chip components
- [x] Add logo components
- [x] Add text input components
- [x] Add modal components
